- name: Create EC2 instance
  hosts: localhost
  connection: local
  gather_facts: no
  remote_user: ubuntu
  vars:
    instance_type: t2.micro
    ami: ami-05b5a865c3579bbc4
    region: eu-west-3
    key_name: karthi.pem
    security_group: sg-0297e091bdd7d9ff3
    tag_name: my-instance
  tasks:
    - name: Provision an EC2 instance with a public IP address
      amazon.aws.ec2_instance:
        name: Demo1
        key_name: "karthi"
        vpc_subnet_id: subnet-05e534524ddc5f5af
        instance_type: t2.micro
        security_group: sg-0297e091bdd7d9ff3
        network:
          assign_public_ip: true
        image_id: ami-05b5a865c3579bbc4
        tags:
          Environment: Testing
      register: result


   # - name: Add EC2 instance to inventory group
    #- lineinfile: line="{{ item.public_ip }} ansible_python_interpreter=/usr/bin/python3" insertafter=EOF dest=./inventory/staging/hosts